version: '3'

services:
  mysql:
    container_name: mysql-standalone-container
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: usersservicedb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always
  user-service-docker:
    image: user-service-docker:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/user-service-docker
    expose:
      - "8762"
    ports:
      - "8762:8762"
    depends_on:
      - mysql
